### PR TITLE
Suppot for geoipasnum and geoiporg

### PR DESCRIPTION
**Pull request by akshayodesk**

### CODE REVIEW

**Comment by msva** [comment]
@akshay2013 can you rebase your work on top of current HEAD, amend unneded "delete" commit, and force-push your PullReq? I think, there will be more chances @agladysh to accept it then.

**Comment by akshayodesk** [comment]
Ok done
Please check

Thanks

**Comment by msva** [comment]
Actually, "delete" commit (and broken initial) is still in place, and, moreover, github still says your branch conflicting with current master.

If you have no objections, I would try to re-do your changes in single commit and will post additional PR when @agladysh will accept that one I already posted :)

**Comment by akshayodesk** [comment]
Thiss is the new  pul request -->
https://github.com/agladysh/lua-geoip/pull/17

**Pull request closed without merging**
