### PR TITLE
Remove the stderr capture and use the GEOIP_SILENCE flag instead

### PR DESCRIPTION
**Pull request by trink**

### CODE REVIEW

**Comment by agladysh** [comment]
Thanks! Please add yourself to the AUTHORS file.

**Comment by agladysh** [comment]
Fixed a few minor things in your commit and merged. Thanks again!

**Comment by trink** [comment]
Sorry I missed the earlier comment in my inbox.  Excellent, thank you.

**Comment by agladysh** [comment]
@trink `GEOIP_SILENCE` flag is not defined in Ubuntu Trusty's geoip-devel. Please provide a workaround and/or an informative error message along with a mention in Readme.

**Comment by trink** [comment]
PR #12

**Pull request closed without merging**
